### ISSUE TITLE
[question] ArchLinux support

### ISSUE THREAD

**Issue by HLFH** [1flow/1flow#34]
Hi,

It would be cool to support ArchLinux as Wallabag did: https://aur.archlinux.org/packages/wallabag/
And what should we do before nginx configuration (https://github.com/1flow/1flow/wiki/Production-setup)? git clone https://github.com/1flow/1flow.git and after, what? Which commands or what steps should we have to setup the 1flow project? Is 1flow compatible with python3 or should we use python2?

Thanks in advance,

**Comment by Karmak23** [comment]
Hi,

1flow is currently tested on python 2 only. I try to code as much as python 3 compatible as possible (eg. using `six` and other py3k recommandations), but I didn't have the time to test it in real conditions yet and have no ETA for this.

I would be glad to help building the pkgfile on IRC or by mail (or here). I could eventually create it in one shot, but I already know I will have no time to maintain it over time, so I avoid to create the frustration of an unmaintained file. 

To install 1flow on Arch, I currently use [sparks](/1flow/sparks) which already supports it. I know this is not “the arch way”, but as I need to install 1flow on many different systems for production purposes, I maintain sparks, and not multi-system/distros install scripts, which would require substantially more work. 

BTW I'm an arch linux user, so I know 1flow works flawlessly on it because it's the system I primarily develop it on.

About the production setup, you have barely nothing more to do than the development one. The documentation will hold performance tuning suggestions and specific setup guides based on various deployment scenarii (eg. one server which holds everything, distributed setup, multi-node setup, etc).

For now, the only thing I can think of is spawning your configuration file based on [the 1flow.io production one](https://github.com/1flow/1flow/blob/master/oneflow/settings/1flow_io.py) instead of [Chani's one](https://github.com/1flow/1flow/blob/master/oneflow/settings/chani.py)— which is my development settings file. This will disable Django's `DEBUG` and will speed up a few things by using a cache engine. These 2 files are currently known working setups, so they are worth investigating if you need something to start from. 

We can elaborate on IRC or by mail if you ever need more help or guidance. As of now I'm 150% busy with twitter feeds and other contractual work since september 2014, so I cannot put more time on community things other than support for newcomers and persons willing to help.

Best regards,

**Comment by HLFH** [comment]
@Karmak23 Thanks!! (I've seen yesterday you created a Docker Hub account...)
